Fix: Rename project to portfolio and update branding

diff --git a/.github/workflows/release-nextjs-app-docker.yml b/.github/workflows/release-nextjs-app-docker.yml
--- a/.github/workflows/release-nextjs-app-docker.yml
+++ b/.github/workflows/release-nextjs-app-docker.yml
@@ -28,7 +28,7 @@ on:
       - '.github/**'
 
 env:
-  IMAGE: nextjs-monorepo-example/nextjs-app
+  IMAGE: portfolio/nextjs-app
 
 permissions:
   contents: read
@@ -36,7 +36,7 @@ permissions:
 jobs:
   docker:
     # Best practice for security (disabled for example, convenient for tools like renovate, dependabot, etc.)
-    # if: ${{ github.repository == 'belgattitude/nextjs-monorepo-example' && contains('refs/heads/main',github.ref)}}
+    # if: ${{ github.repository == 'fbtwitter/portfolio' && contains('refs/heads/main',github.ref)}}
     runs-on: ubuntu-latest
     name: Nextjs-app docker build
     defaults:
@@ -96,9 +96,9 @@ jobs:
           MAX_SIZE_IN_MB: 80
           ZSTD_LEVEL: 8
         run: |
-          zstd -${{ env.ZSTD_LEVEL }} -i ./docker-image.tar -o ./docker-image.tar.zst          
+          zstd -${{ env.ZSTD_LEVEL }} -i ./docker-image.tar -o ./docker-image.tar.zst
           ls -lah | grep docker-image.tar
-          if [ $(ls -s --block-size=1048576 ./docker-image.tar.zst | cut -d' ' -f1)  -gt ${{ env.MAX_SIZE_IN_MB }} ]; then 
-             echo 'Error: docker image too big'; 
-             exit 1; 
+          if [ $(ls -s --block-size=1048576 ./docker-image.tar.zst | cut -d' ' -f1)  -gt ${{ env.MAX_SIZE_IN_MB }} ]; then
+             echo 'Error: docker image too big';
+             exit 1;
           else echo "Size ok"; fi
